
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
